Metaswitch/floki

- Cargo.lock
- Cargo.toml
- docs/content/intro/feature-overview.md
- src/config.rs
- src/errors.rs
- src/image.rs
- src/interpret.rs
- src/main.rs
_I saw this discussed on #floki-users in the Metaswitch slack a while back. This is PR is prompted by the fact that twice in the last week I've checked in a change to a floki file or gitlab CI file, and forgot to change the other of the two..._
This adds the ability to get the image name from a local yaml file, which will make it easier to update/synchronize floki files and gitlab CI files.
I wasn't sure how to add tests for this. What would be sufficient here?
I've tested locally with the following yaml file:
```
foo:
bar:
- baz:
ekidd/rust-musl-builder
baz:
0: ekidd/rust-musl-builder
```
Specifying the following in floki.yaml works:
```
image:
yaml:
file: test.yaml
key: foo.bar.0.baz
```
as does
```
image:
yaml:
file: test.yaml
key: foo.baz.0
```
There's possibly some more complex edge …
> Source image name from local yaml file

- .travis.yml
- CHANGELOG.md
- Cargo.toml
Use the travis cargo deployer to deploy to crates.io.
Also going to add myself to the authors list as a project maintainer.
Closes #20
> Deploy tagged versions to crates.io

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/content/intro/feature-overview.md
- src/command.rs
- src/config.rs
- src/dind.rs
- src/environment.rs
- src/errors.rs
- src/interpret.rs
- src/main.rs
- src/verify.rs
- src/volumes.rs
This starts to address #35, by adding `floki` volumes as outliined in the issue.
> floki volume support

- CHANGELOG.md
- docs/content/intro/feature-overview.md
- src/image.rs
Use case is using floki with the builder dockerfile pattern.
e.g with the following dockerfile, used to build an executable with `docker build -o . .`
```Dockerfile
FROM ekidd/rust-musl-builder:latest AS dev
FROM dev as builder
RUN --mount=target=. \
--mount=id=cargo-git,target=/home/rust/.cargo/git,type=cache,uid=1000,gid=1000 \
--mount=id=cargo-registry,target=/home/rust/.cargo/registry,type=cache,uid=1000,gid=1000 \
--mount=id=cargo-target,target=/home/rust/target,type=cache,uid=1000,gid=1000 \
cargo build --release --locked --target-dir /home/rust/target && cp /home/rust/target/x86_64-unknown-linux-musl/release/using-diesel /home/rust/
FROM scratch
COPY --from=builder /home/rust/using-diesel /
```
`floki` can be configured to launch a container with the dev target in order to launch a …
> Add support for building specific dockerfile target

- CHANGELOG.md
- build.sh
Apparently [[ doesn't exist in the build container, so use sh string
comparison.
Fixes #49
> Use sh string comparison

- CHANGELOG.md
- src/config.rs
- src/dind.rs
- src/image.rs
- src/interpret.rs
- src/main.rs
- src/verify.rs
This fixes #26, and means that a specific `dind` image can be specified in configuration.
> Allow `dind` image to be specified in configuration

- CHANGELOG.md
- src/command.rs
- src/config.rs
- src/dind.rs
- src/image.rs
- src/interpret.rs
- src/volumes.rs
There are places (#60) in `floki` where paths aren't dealt with correctly - there is no guarantee that a path can be utf-8 decoded, but we assume it always can.
This MR uses the correct types with paths, and tidies up some of the code surrounding them. Even if in practice most paths are valid utf-8, this change makes the code more correct, and clearer, as well as avoiding a few unneeded allocations. Correcter, cleaner, faster!
> Better path handling

- CHANGELOG.md
- src/cli.rs
- src/main.rs
> Remove logging verbosity option from CLI to restore working build

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/errors.rs
- src/main.rs
The `structopt` (and indirectly `clap`) upgrade changed how logging etc. was setup. This restores it to original function.
> Restore logging

- CHANGELOG.md
- src/command.rs
- src/interpret.rs
This removes the unsafe conversion to `str` of the working directory,
and also changes the `add_docker_switch` function to uniformly take a
single switch (rather than possibly many, separated by whitespace),
and also to take input which is reference generic over `OsStr`.
> Use proper path types for working directory

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/environment.rs
- src/interpret.rs
The querying of uid and gid always used weird string junk code and a subprocess (lord knows why I did that). This replaces it with the obvious and much more sensible system calls.
In the process I cleaned up some other cruft and put a little structure around the uid/gid pair, just to remove tuple ordering mistakes etc.
> Improve uid/gid queries

- .github/PULL_REQUEST_TEMPLATE.md
Nothing too fancy, I thought it would be worth making a start on some of these basic healthy repository things. I've found these little templates quite nice for lightweight joggers for things that you ought to do on a PR (e.g. run `cargo fmt` - we could do this in CI, but I find this more annoying than anything, especially when more pressing work needs merging).
> Add a basic pull request template

- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- CHANGELOG.md
- README.md
- docs/content/documentation/getting-started.md
- docs/content/intro/feature-overview.md
- docs/content/intro/navigation.md
- floki-hugo.yaml
- src/config.rs
- src/errors.rs
Navigating the [`floki` documentation](https://metaswitch.github.io/floki/) is currently non-trivial, as the format of the documentation is a "blog" and therefore has no clear structure or navigation. Instead content is ordered by date created/modified (as set in the page metadata), and the only form of navigation is from the `README.md` for the project. Also, to test the documentation after editing it, or to test building it after making changes, is not straightforward and requires you to install the tool `hugo`.
This PR aims to add three key improvements to the floki documentation:
1. Make it quick and easy to get an environment for building and testing the `floki` documentation. This seems like a clear example use case for `floki`! Therefore, this is done by adding a `floki-hugo.yaml` …
> Small improvements to the floki documentation navigation and build/test process

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/errors.rs
- src/interpret.rs
At present `floki` doesn't handle quoted arguments properly in the `docker_switches` escape hatch. This adds proper shell compliant parsing of these switches.
Tested by hand
```
docker_switches:
- -e FOO="bar this that other"
```
```
$ ./target/x86_64-unknown-linux-musl/debug/floki run -- echo '$FOO'
bar this that other
```
Error case (missing closing quote):
```
docker_switches:
- -e FOO="bar this that other
```
```
$ ./target/x86_64-unknown-linux-musl/debug/floki run -- echo '$FOO'
23:54:45 [ERROR] A problem occurred: Malformed item in docker_switches: -e FOO="bar this that other
```
I don't think this should break anything that wasn't already broken. It would be nice if this were a little more testable, and more generally I'd like to push the validation (and flattening) of this kind of …
> Fix parsing of docker_switches to adhere to shell quoting rules

- CHANGELOG.md
- docs/content/intro/feature-overview.md
- src/config.rs
- src/interpret.rs
This was motivated by #163.
Unit testing of configuration parsing, live tests of docker container configuration.
I originally added an explicit entrypoint setting key:
```
entrypoint: thing
```
but figured this would probably never be used. If that turns out to be wrong, we should add it back in. `docker_switches` can be used in the meantime.
> Suppress entrypoints by default

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/main.rs
Needed manual intervention to update to a newer API.
Routine dependency update with manual intervention required for an API update.
> Update simplelog to 0.10

- CHANGELOG.md
- src/config.rs
- src/interpret.rs
- src/main.rs
- src/spec.rs
This change breaks apart the two levels of processing that were taking place in the interpret module. This adds a new structure (`FlokiSpec`) which is a fully resolved and checked piece of configuration, which makes building the docker command much more straightforward. Many small procedures can then be inlined or deleted, which generally helps clarity.
Manual runs with various bits of configuration.
None.
- [N/A] Documentation and `README.md` updated for this change, if necessary
> Simplify core processing

- CHANGELOG.md
- docs/content/intro/feature-overview.md
- src/image.rs
It'd be nice to support third party tools that generate docker images (and aren't docker)
Unit testing. I've tested locally as well.
> Add exec mode for generating images

- CHANGELOG.md
- src/errors.rs
This improves the error message around failing to find the ssh-agent socket path - people don't seem to know `SSH_AUTH_SOCK` pertains to having a running ssh-agent configured in the environment (which is fair enough).
What testing has been done?
```
$ unset SSH_AUTH_SOCK
$ ./target/x86_64-unknown-linux-musl/debug/floki
21:02:12 [ERROR] A problem occurred: Unable to forward ssh socket - cannot find SSH_AUTH_SOCK in environment - do you have an ssh agent running?
```
N/A
- [N/A] Documentation and `README.md` updated for this change, if necessary
> Adjust error for failing to find ssh-agent

- CHANGELOG.md
- docs/content/intro/feature-overview.md
- src/dind.rs
- src/image.rs
- src/spec.rs
The `stable-dind` tag doesn't appear to be maintained. Change the default docker image tag to `dind` which appears to be maintained.
Spun up a container with the `dind:true` field in `floki.yaml`. Tested that the docker container used had the tag `dind`. 
> Change stable-dind to dind

- CHANGELOG.md
- src/dind.rs
[!210](https://github.com/Metaswitch/floki/issues/210)
Tested running a docker build with and without the change to confirm that adding the `--tls=false` flag fixes the delay in dind starting up. 
> Set tls=false for dind

- .github/dependabot.yml
- .github/workflows/ci.yml
- build.sh
Seems like github actions have an issue with Ubuntu 18.04. Let's update to 20.04, and also run dependabot for github actions at the same time.
> Update to ubuntu-20.04 and add a dependabot update rule for actions

- CHANGELOG.md
- src/command.rs
Hi! 
This fixes uses of floki in script environments where stdout appears to be a TTY, but stdin is not.
The most basic repro scenario of the problem is:
```
$ echo "" | floki
the input device is not a TTY
10:21:41 [ERROR] A problem occurred: Running container failed: docker run exited with return code 1
```
(I'm not actually trying to pipe anything into floki - the tool I'm using which wants to run floki just doesn't have stdin as a TTY).
Running this with the fix means the above command (and my specific scripted scenario) works correctly.
Didn't see a way to add any regression test to cover this case.
Should be perfectly safe - in any case where stdin was not a TTY, which is the only case this impacts, then floki would have failed.
If you accept, **could you please release a new version …
> Don't add -i to docker command when stdin is not a TTY

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/content/intro/feature-overview.md
- src/config.rs
- src/errors.rs
This exposes some templating support, allowing specifically the ability to use `{{ env.VARIABLE }}` within a floki template to replace that value with the environment variable VARIABLE.
Unit test added
> Floki templates are parsed with `tera` before being deserialized.

- .devcontainer/Dockerfile.alpine
- .devcontainer/devcontainer.json
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- build.sh
- floki.yaml
ekidd/rust-musl-builder is out of date and needs replacing.
CI testing
> Replace rust-musl-builder with more up-to-date builder

- CHANGELOG.md
- src/config.rs
- src/environment.rs
- src/errors.rs
- src/main.rs
Having three sets of errors seemed a bit much.
Unit testing
> Combine errors into a single FlokiError enum.

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/command.rs
- src/interpret.rs
Fixes #62
Local testing:
```
shell:
inner: bash
outer: su - root
```
becomes
```
08:55:42 [DEBUG] (1) floki::command: - and args: ["su", "-", "root", "-c", "bash"]
```
> Use shell_words to split the outer shell so that more complex outer shells can be used.

- .github/workflows/ci.yml
As per https://github.com/actions-rs/toolchain/issues/216, actions-rs is not being actively maintained. Switch to a maintained version.
> Switch out actions-rs toolchain

- .github/workflows/ci.yml
- CHANGELOG.md
- build.sh
- docs/content/intro/feature-overview.md
- src/config.rs
Following the principle of least surprise, don't suppress image entrypoints unless asked to.
Tested with an image that runs an entrypoint before starting the image.
> Allow entrypoints by default

- .github/workflows/ci.yml
The upgrade to actions/up/download artifact v4 need unique names for stages.
> Tweak names of artifact stages so the new artifact actions work

- Cargo.lock
- Cargo.toml
- src/image.rs
yaml-rust is unmaintained and has been replaced by yaml-rust2
> Switch to yaml-rust2 as the yaml-rust crate is no longer maintained.

- CHANGELOG.md
- docs/content/intro/feature-overview.md
- src/interpret.rs
- Add `FLOKI_WORKING_DIR` environment variable that is accessible inside the container. Can be used when `mount:` has been specified in `floki.yaml`.
If someone specifies `mount:` then the assumption that code is mounted at /src is wrong.
Local testing
N/A
> Add `FLOKI_WORKING_DIR` environment variable

- .github/workflows/ci.yml
- build.sh
- floki_sleep.yaml
Ubuntu 20.04 is being deprecated.
> Use new ubuntu
