Metaswitch/floki

- .gitignore
- .gitmodules
- README.md
- docs/archetypes/default.md
- docs/config.toml
- docs/content/documentation/getting-started.md
- docs/content/intro/feature-overview.md
> Start outlining documentation

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/command.rs
- src/config.rs
- src/dind.rs
- src/environment.rs
- src/image.rs
- src/interpret.rs
- src/main.rs
- src/verify.rs
> Update quicli to 0.4

- .travis.yml
- CHANGELOG.md
> Deploy stage in Travis CI

- CHANGELOG.md
- docs/content/intro/feature-overview.md
- src/config.rs
> Make `sh` the default shell

- CHANGELOG.md
- docs/content/intro/feature-overview.md
- src/interpret.rs
> Forward host path as FLOKI_HOST_WORKDIR

- CHANGELOG.md
- src/environment.rs
> Tidy some details in environment module

- CHANGELOG.md
- src/dind.rs
> Disable TLS in dind

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> Version 0.1.0 -> 0.2.0

- src/cli.rs
- src/command.rs
- src/config.rs
- src/dind.rs
- src/environment.rs
- src/errors.rs
- src/image.rs
- src/interpret.rs
- src/main.rs
- src/verify.rs
> Format code

- CHANGELOG.md
- src/config.rs
- src/errors.rs
> Improve parsing of `floki.yaml`

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
> Version 0.2.0 -> 0.3.0

- CHANGELOG.md
- Cargo.toml
- README.md
> Release 0.4.0

- .travis.yml
- CHANGELOG.md
- Cargo.toml
- build.sh
> Attempt to fix up jobs and deployment to Cargo

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
> Release 0.4.1

- .travis.yml
- CHANGELOG.md
- after_deploy.sh
> Add `announce` support for notifying Slack of new changes

- CHANGELOG.md
- Cargo.toml
- README.md
> Release 0.4.2

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- docs/content/documentation/getting-started.md
> Release 0.4.3

- CHANGELOG.md
- src/image.rs
- src/main.rs
A quick fix for https://github.com/Metaswitch/floki/issues/55. I suspect there's something better we can do here - I'll do some thinking when I get the chance, but that probably won't be for a while. See the issue for discussion.
I've very briefly tested this by building an image from a subdirectory, but I'm open to suggestions of any more testing that's necessary. This sort of thing isn't easy to cover in UT; I wonder if there's some easy way to write FVs?
> Resolve Dockerfile path and Docker context relative to floki root

- README.md
So minor that it's hardly worth the commit. It _is_ annoying, though.
> Fix extremely minor (but annoying) typo

- README.md
> Update README with new install instructions

- README.md
Adding a quickstart to make it easier to get started. Also tweaked the
introduction to make it clear that this doesn't replace kubernetes etc.
> Tweak README and add quickstart

- README.md
> Reorganize README to make most useful information more prominent.

- CHANGELOG.md
- src/command.rs
- src/environment.rs
- src/interpret.rs
This is similar to the work to cleanup paths in #61 , and makes the handling of environment variables use the correct types.
> Cleanup handling of environment variables

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- docs/content/documentation/getting-started.md
> Release 0.5.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- docs/content/documentation/getting-started.md
> Release 0.6.0

- .travis.yml
- CHANGELOG.md
- bors.toml
> Add Bors support to floki

- CHANGELOG.md
- docs/content/documentation/getting-started.md
- docs/content/intro/feature-overview.md
I threw together the original documentation on a train journey, and it needed an edit.
I went over and made a bunch of tweaks, and also discovered that `dind` image pinning wasn't documented, so I added that in.
> Various improvements to documentation

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- docs/content/documentation/getting-started.md
> Release 0.6.2

- Cargo.lock
- Cargo.toml
> Cargo updates

- .github/workflows/ci.yml
- Cargo.toml
- bors.toml
- build.sh
> Rudimentary github action to build floki

- .github/workflows/ci.yml
- CHANGELOG.md
> Publish tags to crates.io

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- docs/content/documentation/getting-started.md
> Release 0.7.0

- .github/workflows/ci.yml
> Log in to crates.io

- .github/workflows/ci.yml
- .gitignore
- changelog.sh
> Recreating releases in Github actions

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- docs/content/documentation/getting-started.md
> Release 0.7.1

- .github/workflows/ci.yml
- announce.sh
> Get announces working again

- .github/workflows/ci.yml
- CHANGELOG.md
- src/command.rs
- src/config.rs
- src/environment.rs
- src/image.rs
- src/interpret.rs
- src/main.rs
- src/spec.rs
Having regressible checking for clippy warnings is good practice.
> Fix up clippy warnings and enforce clippy going forward

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- docs/content/documentation/getting-started.md
> Release 0.8.0

- .github/workflows/ci.yml
- Cargo.lock
> Cargo update before tag

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- docs/content/documentation/getting-started.md
- floki_sleep.yaml
> Release 0.9.1

- src/image.rs
> Fix clippy moans

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- docs/content/documentation/getting-started.md
Describe this change, including why it's needed.
What testing has been done?
> Release 1.2.0

- .github/dependabot.yml
> Group upload-artifact and download-artifact action updates

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- announce.sh
- docs/content/documentation/getting-started.md
> Release 2.0.1

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- docs/content/documentation/getting-started.md
> Release 2.1.0
